; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Скорость монитора порта (Serial.begin(115200) в коде)
monitor_speed = 115200

; Скорость заливки прошивки
upload_speed = 921600

; Добавляем корень проекта в пути поиска include,
; чтобы #include "pass.txt" в Ypravlenie.ino работал
; (pass.txt лежит в корне, не в src/)
build_flags =
    -I"${PROJECT_DIR}"

; Внешние библиотеки
lib_deps =
    GyverLibs/GyverDS18
    GyverLibs/FastBot
    marian-craciunescu/ESP32Ping
