; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
build_flags =
    -I"${PROJECT_DIR}"
    -DCORE_DEBUG_LEVEL=0
    -DUSE_ESP_IDF_LOG=1

lib_deps =
    GyverLibs/GyverDS18
    marian-craciunescu/ESP32Ping
    bblanchon/ArduinoJson
    yasheena/TelnetSpy


[env:esp32ota]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
build_flags =
    -I"${PROJECT_DIR}"
    -DCORE_DEBUG_LEVEL=0  ;0 - откл полностью, 5 - вкл все (ERROR-WARN-INFO-DEBUG-VERBOSE). Подкапотные логи сетевых и иных системных библиотек!
    -DUSE_ESP_IDF_LOG=1   ; использовать методы логирования из ESP_IDF, а не из фреймворка Arduino (log_x)
lib_deps =
    GyverLibs/GyverDS18
    marian-craciunescu/ESP32Ping
    bblanchon/ArduinoJson
    yasheena/TelnetSpy

upload_protocol = espota
extra_scripts = pre:scripts/OTA_secrets.py
monitor_speed=115200
upload_speed=921600