; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600
build_flags =
    -I"${PROJECT_DIR}"

lib_deps =
    GyverLibs/GyverDS18
    marian-craciunescu/ESP32Ping
    bblanchon/ArduinoJson
    yasheena/TelnetSpy


[env:esp32ota]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
    -I"${PROJECT_DIR}"
lib_deps =
    GyverLibs/GyverDS18
    marian-craciunescu/ESP32Ping
    bblanchon/ArduinoJson
    yasheena/TelnetSpy

upload_protocol = espota
upload_port = ESP32_Home.local
upload_flags = --auth=AlexHome
monitor_speed=115200
upload_speed=921600